run:
  timeout: 3m

linters:

  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

    - goimports
    - gofmt

linters-settings:

  goimports:
    local-prefixes: github.com/zhavkk/L0-test-service

issues:
  exclude-use-default: false

  max-same-issues: 0