name: CI

on:
  push:
    branches: [main,dev]
  pull_request:
    branches: [main,dev]

  
jobs:
  go-lint:
    name: Go lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: false

      - name: Install dependencies
        run: make go-deps

      - name: Run golangci-lint
        run: make go-lint
  