name: CI

on:
  push:
    branches: [main,dev]
  pull_request:
    branches: [main,dev]

  
jobs:
  go-lint:
    name: Go lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: false

      - name: Install dependencies
        run: make go-deps

      - name: Run golangci-lint
        run: make go-lint
  
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: order_service_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        env:
          DB_URL: "postgres://postgres:postgres@localhost:5432/order_service_test?sslmode=disable"
        run: make go-test